<?php
require_once __DIR__.'/includes/bootstrap.php'; require_admin();
$notice=''; $error='';
if(is_post()){
 verify_csrf(); $id=(int)($_POST['id']??0); $action=$_POST['action']??'';
 try{
  if(!$db) throw new RuntimeException('Database unavailable.');
  if($action==='retry' || $action==='complete'){
   if($action==='retry'){$db->prepare("UPDATE provisioning_jobs SET status='queued',error_message=NULL WHERE id=? AND status='failed'")->execute([$id]);$notice='Job returned to the provisioning queue.';}
   else {$r=provision_job($db,$id); if($r['ok'])$notice=$r['message']; else $error=$r['message'];}
  } elseif($action==='cancel'){$db->prepare("UPDATE provisioning_jobs SET status='cancelled',admin_note=? WHERE id=?")->execute([trim($_POST['note']??''),$id]);$notice='Provisioning job cancelled.';}
  else throw new RuntimeException('Invalid action.');
 }catch(Throwable $e){$error=$e->getMessage();}
}
$rows=$db?$db->query("SELECT pj.*,o.order_number,oi.description,oi.item_type,oi.domain_name,u.full_name,u.email FROM provisioning_jobs pj JOIN orders o ON o.id=pj.order_id LEFT JOIN order_items oi ON oi.id=pj.order_item_id LEFT JOIN users u ON u.id=pj.user_id ORDER BY pj.id DESC")->fetchAll():[];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Provisioning Queue — WDH</title><link rel="stylesheet" href="assets/css/style.css?v=wdh-ui-v8"><link rel="stylesheet" href="assets/css/catalog.css?v=wdh-ui-v8"></head><body><?php require __DIR__.'/includes/header.php';?><main class="admin-page"><div class="portal-welcome"><div><span class="eyebrow mint">ADMIN OPERATIONS</span><h1>Provisioning Queue</h1><p>Track paid orders that need domain or service activation. External APIs are only called when configured.</p></div><div class="actions"><a class="btn secondary" href="admin.php">Admin Dashboard</a></div></div><?php if($notice):?><div class="alert success-alert"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><div class="admin-table"><?php if(!$rows):?><div class="empty">No provisioning jobs are queued yet.</div><?php else:foreach($rows as $r):?><div class="admin-row"><div><strong><?=e($r['description']??'Service')?></strong><small><?=e($r['order_number'])?> · <?=e($r['full_name']??'')?> · <?=e($r['email']??'')?></small></div><span><?=e($r['job_type'])?></span><span><?=e(ucfirst($r['status']))?></span><small><?=e($r['provider'])?><?php if($r['error_message']):?> · <?=e($r['error_message'])?><?php endif;?></small><div class="actions"><?php if($r['status']==='failed'):?><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="action" value="retry"><button class="btn secondary small">Retry</button></form><?php elseif(in_array($r['status'],['queued','processing'],true)):?><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="action" value="complete"><button class="btn primary small">Process</button></form><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="action" value="cancel"><button class="btn secondary small">Cancel</button></form><?php endif;?></div></div><?php endforeach;endif;?></div></main><?php require __DIR__.'/includes/footer.php';?></body></html>
