<?php
require_once __DIR__.'/includes/bootstrap.php'; require_admin();
$notice=''; $error='';
$definitions=[
 'business_name'=>['Business Name','text',1], 'support_email'=>['Support Email','email',1], 'support_phone'=>['Support Phone','text',1],
 'default_server_markup'=>['Default Server Markup (%)','number',0], 'default_service_currency'=>['Default Service Currency','text',0],
 'manual_fulfillment_enabled'=>['Manual Fulfillment Enabled','boolean',0], 'domain_api_mode'=>['Domain API Mode','text',0], 'maintenance_mode'=>['Maintenance Mode','boolean',0], 'live_chat_provider'=>['Live Chat Provider','text',1], 'live_chat_property_id'=>['Live Chat Property ID','text',0], 'live_chat_widget_id'=>['Live Chat Widget ID','text',0], 'live_chat_enabled'=>['Live Chat Enabled','boolean',1]
];
function setting_get($db,$key,$fallback=''){ if(!$db)return $fallback; try{$s=$db->prepare('SELECT setting_value FROM site_settings WHERE setting_key=? LIMIT 1');$s->execute([$key]);$v=$s->fetchColumn();return $v===false?$fallback:$v;}catch(Throwable $e){return $fallback;} }
if(is_post()){verify_csrf(); try{foreach($definitions as $key=>$meta){$value=$_POST[$key]??''; if($meta[1]==='boolean')$value=isset($_POST[$key])?'1':'0'; if($meta[1]==='email' && $value!=='' && !filter_var($value,FILTER_VALIDATE_EMAIL))throw new InvalidArgumentException('Invalid support email.'); if($key==='default_server_markup' && (!is_numeric($value)||$value<0||$value>200))throw new InvalidArgumentException('Markup must be between 0 and 200.'); $st=$db->prepare('INSERT INTO site_settings(setting_key,setting_value,setting_type,is_public,updated_by) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),setting_type=VALUES(setting_type),is_public=VALUES(is_public),updated_by=VALUES(updated_by)');$st->execute([$key,(string)$value,$meta[1],$meta[2],(int)current_user()['id']]);}$notice='Settings saved successfully.';}catch(Throwable $e){$error=$e->getMessage();}}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Settings — WDH</title><link rel="stylesheet" href="assets/css/style.css?v=wdh-ui-v8"><link rel="stylesheet" href="assets/css/catalog.css?v=wdh-ui-v8"></head><body><?php require __DIR__.'/includes/header.php';?><main class="admin-page"><div class="portal-welcome"><div><span class="eyebrow mint">ADMIN CONTROL CENTER</span><h1>Business Settings</h1><p>Manage operational defaults without editing application code.</p></div><div class="actions"><a class="btn secondary" href="admin.php">Pricing</a><a class="btn secondary" href="admin-reports.php">Reports</a></div></div><?php if($notice):?><div class="alert success-alert"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><form method="post" class="admin-section"><?=csrf_field()?><div class="admin-table settings-grid"><?php foreach($definitions as $key=>$meta):$v=setting_get($db,$key,'');?><label><?=e($meta[0])?><?php if($meta[1]==='boolean'):?><span><input type="checkbox" name="<?=e($key)?>" value="1" <?=$v==='1'?'checked':''?>> Enabled</span><?php else:?><input type="<?=e($meta[1])?>" name="<?=e($key)?>" value="<?=e($v)?>" <?=in_array($meta[1],['email','number'],true)?'required':''?>><?php endif;?></label><?php endforeach;?></div><p class="muted">Provider credentials, API keys, Secret Purchase Notes and encryption keys are intentionally not editable from this public settings screen.</p><button class="btn primary">Save Settings</button></form></main><?php require __DIR__.'/includes/footer.php';?></body></html>
