<?php
require_once __DIR__.'/includes/bootstrap.php'; require_login();
$u=current_user(); $id=(int)($_GET['id']??0); $error=''; $notice=''; $r=null;
if($db){$st=$db->prepare('SELECT * FROM customer_services WHERE id=? AND user_id=? LIMIT 1');$st->execute([$id,$u['id']]);$r=$st->fetch();}
if(!$r){http_response_code(404);exit('Service not found.');}
if((float)$r['renewal_price']<=0 || $r['renewal_cycle']==='none'){
  http_response_code(400); exit('Renewal is not configured for this service.');
}
if(strtoupper((string)$r['renewal_currency'])!=='BDT'){
  http_response_code(400); exit('Account-balance renewal currently supports BDT services only.');
}
if(false){http_response_code(400);exit('Renewal is not configured for this service.');}
if(is_post()){verify_csrf();try{$db->beginTransaction();$st=$db->prepare('SELECT * FROM customer_services WHERE id=? AND user_id=? FOR UPDATE');$st->execute([$id,$u['id']]);$r=$st->fetch();$st=$db->prepare('SELECT account_balance FROM users WHERE id=? FOR UPDATE');$st->execute([$u['id']]);$balance=(float)$st->fetchColumn();$price=(float)$r['renewal_price'];if($balance<$price)throw new RuntimeException('Insufficient account balance. Please add funds first.');$old=$r['expires_at'] && strtotime($r['expires_at'])>time()?new DateTime($r['expires_at']):new DateTime('today');$interval=$r['renewal_cycle']==='monthly'?new DateInterval('P1M'):new DateInterval('P1Y');$old->add($interval);$db->prepare('UPDATE users SET account_balance=account_balance-? WHERE id=?')->execute([$price,$u['id']]);$db->prepare('INSERT INTO balance_transactions(user_id,type,amount,reference,status) VALUES(?,?,?,?,?)')->execute([$u['id'],'renewal_payment',$price,'Service Renewal #'.$id,'approved']);$db->prepare('UPDATE customer_services SET expires_at=?,status="active" WHERE id=?')->execute([$old->format('Y-m-d'),$id]);$db->commit();$serviceForNotice=$r;$serviceForNotice['expires_at']=$old->format('Y-m-d');$serviceForNotice['email']=$u['email']??'';wdh_customer_message($db,$u,'Service Renewed Successfully','Your service \"'.($r['service_name']??'Service').'\" has been renewed until '.$old->format('Y-m-d').'.','manage-service.php?id='.$id,'service_renewed',null,$id);$notice='Service renewed successfully until '.$old->format('Y-m-d').'.';}catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error=$e->getMessage();}}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Renew Service — WDH</title><link rel="stylesheet" href="assets/css/style.css?v=wdh-ui-v8"><link rel="stylesheet" href="assets/css/catalog.css?v=wdh-ui-v8"></head><body><?php require __DIR__.'/includes/header.php';?><main class="simple-page"><div class="breadcrumbs">Home › My Services › Renewal</div><div class="portal-welcome"><div><span class="eyebrow mint">SERVICE RENEWAL</span><h1>Renew <?=e($r['service_name'])?></h1><p>Pay from your WDH account balance.</p></div></div><?php if($notice):?><div class="alert success-alert"><?=e($notice)?></div><?php else:?><section class="cart-card" style="max-width:720px"><div class="dashboard-grid"><div class="dash-card"><span>Renewal Price</span><strong><?=money($r['renewal_price'],$r['renewal_currency'])?></strong></div><div class="dash-card"><span>Current Balance</span><strong><?=money((float)$u['account_balance'],'BDT')?></strong></div></div><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><form method="post"><?=csrf_field()?><p>You can renew this service using your account balance. The payment will be recorded in your transaction history.</p><button class="btn primary">Confirm Renewal →</button></form></section><?php endif;?><a class="btn secondary" href="my-services.php">Back to Services</a></main><?php require __DIR__.'/includes/footer.php';?></body></html>
