CREATE TABLE IF NOT EXISTS invoices (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 order_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NULL,
 invoice_number VARCHAR(40) NOT NULL,
 subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
 tax DECIMAL(12,2) NOT NULL DEFAULT 0,
 total DECIMAL(12,2) NOT NULL DEFAULT 0,
 currency CHAR(3) NOT NULL DEFAULT 'BDT',
 status VARCHAR(30) NOT NULL DEFAULT 'unpaid',
 due_at DATETIME NULL,
 paid_at DATETIME NULL,
 created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id), UNIQUE KEY uq_invoice_number(invoice_number), UNIQUE KEY uq_invoice_order(order_id), KEY idx_invoice_user(user_id), KEY idx_invoice_status(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS refunds (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 order_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 amount DECIMAL(12,2) NOT NULL,
 reason VARCHAR(255) DEFAULT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'requested',
 admin_note VARCHAR(255) DEFAULT NULL,
 created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id), KEY idx_refund_order(order_id), KEY idx_refund_user(user_id), KEY idx_refund_status(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
