SET @db := DATABASE();
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE customer_services ADD COLUMN login_password_enc TEXT NULL AFTER username','SELECT 1') FROM information_schema.columns WHERE table_schema=@db AND table_name='customer_services' AND column_name='login_password_enc'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE customer_services ADD COLUMN email_login_url VARCHAR(255) NULL AFTER login_password_enc','SELECT 1') FROM information_schema.columns WHERE table_schema=@db AND table_name='customer_services' AND column_name='email_login_url'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE customer_services ADD COLUMN email_username VARCHAR(120) NULL AFTER email_login_url','SELECT 1') FROM information_schema.columns WHERE table_schema=@db AND table_name='customer_services' AND column_name='email_username'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE customer_services ADD COLUMN email_password_enc TEXT NULL AFTER email_username','SELECT 1') FROM information_schema.columns WHERE table_schema=@db AND table_name='customer_services' AND column_name='email_password_enc'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE customer_services ADD COLUMN renewal_price DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER expires_at','SELECT 1') FROM information_schema.columns WHERE table_schema=@db AND table_name='customer_services' AND column_name='renewal_price'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE customer_services ADD COLUMN renewal_currency CHAR(3) NOT NULL DEFAULT ''BDT'' AFTER renewal_price','SELECT 1') FROM information_schema.columns WHERE table_schema=@db AND table_name='customer_services' AND column_name='renewal_currency'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE customer_services ADD COLUMN renewal_cycle VARCHAR(20) NOT NULL DEFAULT ''yearly'' AFTER renewal_currency','SELECT 1') FROM information_schema.columns WHERE table_schema=@db AND table_name='customer_services' AND column_name='renewal_cycle'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE customer_services ADD COLUMN notes VARCHAR(500) NULL AFTER renewal_cycle','SELECT 1') FROM information_schema.columns WHERE table_schema=@db AND table_name='customer_services' AND column_name='notes'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
