CREATE TABLE IF NOT EXISTS auth_rate_limits (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 identifier VARCHAR(190) NOT NULL,
 ip_address VARCHAR(45) NULL,
 attempts INT UNSIGNED NOT NULL DEFAULT 0,
 window_started_at DATETIME NOT NULL,
 blocked_until DATETIME NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id), UNIQUE KEY uq_auth_identifier(identifier), KEY idx_auth_ip(ip_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
